import React from "react";
import Layout from "@/components/layout/layout";
function terms_of_service() {
  return (
    <Layout>
      <div className="container mt-16 flex h-screen flex-col space-y-4 text-lg">
        <p>
          Introduction:This terms of use agreement (the "Agreement") governs
          your access to and use of the AI writing services (the "Services")
          provided by [Company Name], a [State] corporation (the "Company").
        </p>
        <p>
          By accessing or using the Services, you agree to be bound by the terms
          and conditions set forth in this Agreement. If you do not agree to
          these terms, you may not use the Services. Use of the Services:The
          Services are for personal, non-commercial use only.
        </p>
        <p>
          You may use the Services to generate writing content for your own
          personal use, but you may not use the Services for any commercial
          purposes, including but not limited to generating content for
          websites, blogs, advertisements, or marketing materials. We will not
          be offering refunds unless there is a significant bug caused by our
          software (must provide proof).{" "}
        </p>
        <p>
          Proprietary Rights:The Services and all content generated by the
          Services are protected by copyright, trademark, and other intellectual
          property laws. The Company owns all rights, title, and interest in and
          to the Services, including all proprietary and confidential
          information, and you may not copy, modify, or distribute any of the
          Services or content generated by the Services.
        </p>
        <p>
          {" "}
          Disclaimer of Warranties:The Services are provided "as is" and "as
          available," and the Company makes no representation or warranty of any
          kind, express or implied, including but not limited to the accuracy,
          reliability, or completeness of the Services or content generated by
          the Services. The Company assumes no responsibility for any errors or
          omissions in the Services or content generated by the Services.
        </p>
        <p>
          Limitation of Liability:The Company shall not be liable for any
          damages, including but not limited to direct, indirect, incidental,
          special, or consequential damages, arising from the use of or
          inability to use the Services, or for any errors or omissions in the
          Services or content generated by the Services. Conch is is not
          responsible for any disciplinary actions taken by educational
          institutions against our customers.{" "}
        </p>
        <p>
          Termination:The Company may terminate this Agreement and your use of
          the Services at any time and for any reason, without notice. Governing
          Law:This Agreement shall be governed by and construed in accordance
          with the laws of the State of Deleware.
        </p>
        <p>
          Entire Agreement:This Agreement constitutes the entire agreement
          between you and the Company and supersedes all prior agreements or
          understandings, whether written or oral, relating to the use of the
          Services. By accessing or using the Services, you acknowledge that you
          have read and agree to be bound by the terms and conditions of this
          Agreement.
        </p>
      </div>
    </Layout>
  );
}

export default terms_of_service;
